### ISSUE TITLE
Flarum MathRen extension

### ISSUE THREAD

**Issue by rmolives** [FreeFlarum/freeflarum.com#193]
**Packagist URL:** https://packagist.org/packages/the-turk/flarum-mathren

Not compatible with beta.15 yet, one user should finish the compatible fork by the end of March 2021 (as the original author is busy and won't likely make it compatible soon).

**Comment by CWKevo** [comment]
1. Please follow the template.
2. Incompatible with the current Flarum version: https://discuss.flarum.org/d/22439

One user stated that they're making it compatible and it should be ready by the end of March 2021 (https://discuss.flarum.org/d/22439/77). Until then, please be patient.

**Comment by MisaWki** [comment]
okay, thank you

**Comment by CWKevo** [comment]
This fork seems to be updated now, and will be included when we update to beta.16: https://github.com/StarsRivers/flarum-mathren/

**Comment by CWKevo** [comment]
I have tried adding the above mentioned https://extiverse.com/extension/starsriver/mathplus as an alternative, which doesn't work (or I don't know how to use it).

Feel free to try it out when your forum gets synced and the extension becomes available for you. Unfortunately, there are no math rendering extensions currently available for Flarum, so I'll keep this open anyways. Maybe MathRen updates, someday...

**Comment by CWKevo** [comment]
Replaced `starsriver/mathplus` with `the-turk/flarum-mathren`.

**Comment by CWKevo** [comment]
Temporarily removed from all FreeFlarum forums, please see https://discuss.flarum.org/d/7585/3952 for details. The extension will be re-added when it becomes compatible with Flarum v1.5.0.

**Comment by CWKevo** [comment]
Installed in favor of #413
