### ISSUE TITLE
Likes Received

### ISSUE THREAD

**Issue by ghost** [FreeFlarum/freeflarum.com#220]
Hi is possible  test and maybe add this extension ? Counts the number of received likes.
It doesn't seem to be system-intensive and shouldn't be a problem.
https://discuss.flarum.org/d/24489-likes-received

Thank you for the check

__Packagist URL for extension:__
https://packagist.org/packages/clarkwinkelmann/flarum-ext-likes-received
https://github.com/clarkwinkelmann/flarum-ext-likes-received

**Comment by CWKevo** [comment]
Included

**Comment by sfc90** [comment]
Thanks, plugin is great, looks perfect. It just doesn't load previous likes, it only reads new ones after turning on the plugin. I have already contacted the author and reported it.

**Comment by CWKevo** [comment]
That's because it's a simple extension. Its discussion states that you must run the `php flarum clarkwinkelmann:likes-received:refresh
` command to recalculate likes. If you tell me your forum name, I'll run it for you (since you can't).

**Comment by Romantomenko777** [comment]
https://support.freeflarum.com/d/31-d24489-likes-received
