### ISSUE TITLE
Requesting moderator-notes

### ISSUE THREAD

**Issue by Kaleb99jOfficial** [FreeFlarum/freeflarum.com#286]
__Packagist URL for extension:__
https://packagist.org/packages/fof/moderator-notes

__Why should we install the extension?__
Adds private notes for Moderators and Administrators to put on accounts. (From my understanding anyway. The description says for forum users but the name is Moderator Notes.)

**Comment by CWKevo** [comment]
Removed ([ref.](https://discuss.flarum.org/d/7585/4155))
