### ISSUE TITLE
hehongyuanlove/flarum-auth-qq

### ISSUE THREAD

**Issue by essesoul** [FreeFlarum/freeflarum.com#310]
__Packagist URL for extension:__
composer require hehongyuanlove/flarum-auth-qq:*

__Why should we install the extension?__
A Flarum extension. Allow users to log in with QQ

**Comment by CWKevo** [comment]
It requires `flarum/core` with `*` constraint, which means any version (including the beta ones). It also doesn't take advantage of the [FoF OAuth](https://github.com/FriendsOfFlarum/oauth#extending) extension. Even though the last code was pushed 2 months ago, there are some folders from 2 years ago, indicating that it might be an outdated extension. I therefore assume that this will cause issues with the new OAuth extension, so I'm not including it for now.

**Comment by SKevo18** [comment]
Closing, for reasons above. If the extension is fixed, a new request can be made at https://support.freeflarum.com/t/extension-requests
