### ISSUE TITLE
webbinaro/gpx-preview

### ISSUE THREAD

**Issue by Profi420** [FreeFlarum/freeflarum.com#325]
__Packagist URL for extension:__
https://packagist.org/packages/webbinaro/gpx-preview

__Why should we install the extension?__
preview map of gpx files

**Comment by CWKevo** [comment]
Added

**Comment by CWKevo** [comment]
Removed. [Ref.](https://discuss.flarum.org/d/7585/3828)

**Comment by CWKevo** [comment]
Possible alternative: https://discuss.flarum.org/d/31732

**Comment by SKevo18** [comment]
Closing in favour of #435
