### ISSUE TITLE
zerosonesfun/composer-preview

### ISSUE THREAD

**Issue by Me0wCat** [FreeFlarum/freeflarum.com#364]
__Packagist URL for extension:__
https://packagist.org/packages/zerosonesfun/composer-preview

__Why should we install this extension?__
...

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum.
---

**Comment by CWKevo** [comment]
Please, follow the template - why should we install this extension?

Flarum has a preview button included by default in the core. If you want to have a WYSIWYG editor, you may also use the Rich Text extension as an alternative, which is already available at FreeFlarum.

**Comment by Romantomenko777** [comment]
https://support.freeflarum.com/d/29-zerosonesfuncomposer-preview
