### ISSUE TITLE
davwheat/whispermaintainer/

### ISSUE THREAD

**Issue by Profi420** [FreeFlarum/freeflarum.com#365]
since whisper is not working anymore - here is a fork:

I do have a forked version of Whisper which solves some issues which people have faced: https://github.com/davwheat/whisper You'd need to set up a workbench repository in your composer.json then manually git clone it to your Flarum instance to use it, though, and I don't plan on actively supporting it with features or bugfixes at the moment
https://discuss.flarum.org/d/30933-who-could-fix-pm-for-flarum/14

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum.
---

**Comment by SKevo18** [comment]
This fork doesn't seem to be actively maintained though (last commit was 2 years ago), so I am unfortunately a bit hesitant to include this right now. But I guess I could try to check if it works, and if there are no issues, I'll keep it. I'll get back to this one later

**Comment by SKevo18** [comment]
The fork you shared is not actively maintained anymore (last commit: 3 years ago). I've opened a new request here that includes latest fork: https://support.freeflarum.com/d/34
