### ISSUE TITLE
blomstra/email-conversations

### ISSUE THREAD

**Issue by orschiro** [FreeFlarum/freeflarum.com#366]
__Packagist URL for extension:__
https://packagist.org/packages/blomstra/email-conversations

__Why should we install the extension?__
Like with Github, it allows users to reply to conversations by email which is a great integration.

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum.
---

**Comment by CWKevo** [comment]
Installed

**Comment by SKevo18** [comment]
Also:

> At present, you must be using [Mailgun](https://www.mailgun.com/) to send your email notifications (using the built in Mailgun provider). Support for other services might be added in the future, but for now this will be the only provider option.

As this extension still seems to be in the beta phase, I will once again reconsider adding it in the future once it becomes more mature

**Comment by SKevo18** [comment]
Closing this for now, for the same reason as #362

**Comment by SKevo18** [comment]
Will reopen again at https://support.freeflarum.com when this becomes an official extension (right now, it is still in beta)
