### ISSUE TITLE
tokenjenny/flarum-ext-web3

### ISSUE THREAD

**Issue by SKevo18** [FreeFlarum/freeflarum.com#369]
__Packagist URL for extension:__
https://packagist.org/packages/tokenjenny/flarum-ext-web3

*Based on an E-mail request.*

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum.
---

**Comment by Romantomenko777** [comment]
https://support.freeflarum.com/d/28-tokenjennyflarum-ext-web3
