### ISSUE TITLE
datlechin/flarum-more-discussions 

### ISSUE THREAD

**Issue by Profi420** [FreeFlarum/freeflarum.com#372]
__Packagist URL for extension:__
https://packagist.org/packages/datlechin/flarum-more-discussions

__Why should we install the extension?__
A [Flarum](http://flarum.org/) extension. Add a custom discussion list to the bottom's discussion page.

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum.
---

**Comment by CWKevo** [comment]
Added!
