### ISSUE TITLE
Mark Unread

### ISSUE THREAD

**Issue by orschiro** [FreeFlarum/freeflarum.com#373]
## Packagist URL for extension

`https://packagist.org/packages/blomstra/mark-unread`

## Why should we install the extension?

It's quite an established feature to mark conversations as unread to revisit them at a later stage. :)

Would make a nice addition!

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum.
---

**Comment by CWKevo** [comment]
Added
