### ISSUE TITLE
Chinese Traditional Language Pack

### ISSUE THREAD

**Issue by SpookyKipper** [FreeFlarum/freeflarum.com#374]
## Packagist URL for extension

`https://packagist.org/packages/csineneo/lang-traditional-chinese`

## Why should we install the extension?

It would be great to have a Chinese Traditional Translation installed and not only the simplified one.
It will definitely benefit Hong Kong and Taiwan Users.
https://discuss.flarum.org/d/17954-chinese-language-pack

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum.
---

**Comment by keyang556** [comment]
use this  https://github.com/flarum-lang/chinese-traditional
