### ISSUE TITLE
Flarum Discussion overview

### ISSUE THREAD

**Issue by shawny43** [FreeFlarum/freeflarum.com#376]
## Packagist URL for extension:

https://packagist.org/packages/datlechin/flarum-discussion-overview

## Why should this extension be installed?

Show the status of the current post. 
https://discuss.flarum.org/d/31265-discussion-overview

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum. Does not apply to extension updates or "re-installations".
---

**Comment by Romantomenko777** [comment]
https://support.freeflarum.com/d/27-datlechinflarum-discussion-overview
