### ISSUE TITLE
FontAwesome 6 (fontawesome/blomstra)

### ISSUE THREAD

**Issue by shawny43** [FreeFlarum/freeflarum.com#378]
## Packagist URL for extension:

https://packagist.org/packages/blomstra/fontawesome

## Why should this extension be installed?

Update FontAwesome to V6 instead of V5.

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum. Does not apply to extension updates or "re-installations".
---

**Comment by CWKevo** [comment]
Added
