### ISSUE TITLE
flarum-ext-status

### ISSUE THREAD

**Issue by Softenix** [FreeFlarum/freeflarum.com#382]
## Packagist URL for extension:

https://extiverse.com/extension/clarkwinkelmann/flarum-ext-status
## Why should this extension be installed?

Seems like a cool feature to have when you want a forum with more social interactions between users

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum. Does not apply to extension updates or "re-installations".
---

**Comment by CWKevo** [comment]
Installed
