### ISSUE TITLE
 justoverclock/flarum-ext-keywords

### ISSUE THREAD

**Issue by Profi420** [FreeFlarum/freeflarum.com#387]
### URL to the extension:

https://extiverse.com/extension/justoverclock/flarum-ext-keywords

### Why should this extension be installed?

This extension maps the words written in the posts and allows you to build a real glossary for your website.

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum. Does not apply to extension updates or "re-installations".
---

**Comment by Romantomenko777** [comment]
https://support.freeflarum.com/d/26-justoverclockflarum-ext-keywords
