### ISSUE TITLE
fof/follow-tags

### ISSUE THREAD

**Issue by pschaffl** [FreeFlarum/freeflarum.com#388]
### URL to the extension:

https://discuss.flarum.org/d/20525-friendsofflarum-follow-tags

### Why should this extension be installed?

I need to be notified about all new discussions and posts in the forum.

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum. Does not apply to extension updates or "re-installations".
---

**Comment by CWKevo** [comment]
Duplicate of #363 and #63
