### ISSUE TITLE
Justoverclock / first-visit-indexpage

### ISSUE THREAD

**Issue by shawny43** [FreeFlarum/freeflarum.com#389]
### URL to the extension:
https://packagist.org/packages/justoverclock/first-visit-indexpage

### Why should this extension be installed?

A new way to show off some rules quickly by redirect new users. 

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum. Does not apply to extension updates or "re-installations".
---

**Comment by medelinor-1** [comment]
Hello

May I know if the team has responded to you, or added the extension you requested to the forum?

**Comment by CWKevo** [comment]
> Hello
> 
> May I know if the team has responded to you, or added the extension you requested to the forum?

All extensions are added globally for all forums once their requests in this repository receive at least 5 upvotes (👍). When that happens, an update will be posted and the issue will be closed. So if you are interested in this extension, please upvote this issue.

**Comment by SKevo18** [comment]
Added
