### ISSUE TITLE
irmmr/flarum-ext-rtl

### ISSUE THREAD

**Issue by medelinor-1** [FreeFlarum/freeflarum.com#390]
### URL to the extension:
[https://packagist.org/packages/irmmr/flarum-ext-rtl](https://packagist.org/packages/irmmr/flarum-ext-rtl
)

### Why should this extension be installed?
It is necessary to add this extension because it is one of the main extensions for languages that are written from right to left.

Can't post to the forum or attract people to it because this extension was removed after the last update.

I think this is a basic extension that is meant to be so that it doesn't get in the way of right-to-left language forums and so that there is encouragement to use Flarum by other communities.

This extension is directly related to the user experience who reads languages from right to left, such as Arabic and Hebrew

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum. Does not apply to extension updates or "re-installations".
---

**Comment by Adhamahmeddd** [comment]
interested

**Comment by CWKevo** [comment]
> interested

Please, upvote the issue. All extensions require at least 5 👍 in order to be included at FreeFlarum.

**Comment by medelinor-1** [comment]
Thank you dear @CWKevo 

**Originally** this is not an add-on request, this is a **re-install request**, because the extension was there before, and it was removed after a problem with the forum.

Extension is very necessary

I will try to find those who are interested to vote and express their opinion

**Thank you**

**Comment by CWKevo** [comment]
> **Originally** this is not an add-on request, this is a **re-install request**, because the extension was there before, and it was removed after a problem with the forum.

If that's the case, I've re-installed it right now

**Comment by medelinor-1** [comment]
thank you dear @CWKevo 

The extension has been installed and the issue has been resolved.

**Thank you very much**
