### ISSUE TITLE
Please add hebrew extension

### ISSUE THREAD

**Issue by hamalrad** [FreeFlarum/freeflarum.com#4]
Please add hebrew extension: 
https://discuss.flarum.org/d/6473-hebrew-translation

Thank you!

**Comment by gwillem** [comment]
There's no beta9 compatible version right now...

**Comment by itayganor** [comment]
this is the latest available version of the Hebrew translation: https://github.com/itayganor/flabrew
If you know where to find the new beta9 strings, let me know!

**Comment by xCustomWorld** [comment]
But does it work with beta.10 now @itayganor ? 🤔
Now there will be paradox, everytime they update the exension, Flarum will update too xP

I have checked the GitHub and it is your extension. The read me also says "Work in progress...". I recommend you to do more tests and to finish the extension and then make a new request of the extension.

**Comment by itayganor** [comment]
I'm currently trying to find an example for a beta.10 locale files to begin updating the extension.
If you know where to find them, I'd be glad to know

**Comment by xCustomWorld** [comment]
You mean [these](https://github.com/flarum/lang-english)?

If you need further help, contact me at Discord (CustomWorld#5551) or send me a mail (support@customworld.xyz), PM me or whatever, because this is not kinda a place to ask for extension help :')

**Comment by SKevo18** [comment]
Added `flarum-lang/hebrew`
