### ISSUE TITLE
FoF Discussion Language

### ISSUE THREAD

**Issue by fcodonlucas** [FreeFlarum/freeflarum.com#400]
URL to the extension:

https://packagist.org/packages/fof/discussion-language

Why should this extension be installed?

Make different language contents is very important.

**Comment by Borderliner** [comment]
No progress?

**Comment by SKevo18** [comment]
Normally, I wouldn't include this as it has not the required amount of upvotes, but since I remember this extension being at FreeFlarum before, I am going to include it again, as people have shown interest in having it at FreeFlarum.

Added
