### ISSUE TITLE
Please add the extention Title lenght

### ISSUE THREAD

**Issue by Alfaromeoman** [FreeFlarum/freeflarum.com#406]
### URL to the extension:

https://packagist.org/packages/datlechin/flarum-title-length

### Why should this extension be installed?

 The title of 80 characters is too short users may need more characters for a detailed title

---
> ###### **Note**: All new extension requests require at least 5 upvotes (👍) before they can be added to FreeFlarum. If you are interested in this extension, please upvote this issue by adding the "👍" reaction to this comment. [Why?](https://discuss.flarum.org/d/7585/3828#:~:text=as%20a%20result%20of%20this%2C%20all%20extension%20requests%20must%20now%20provide%20a%20valid%20reason%20why%20should%20that%20extension%20be%20installed%2C%20and%20must%20have%20at%20least%205%20upvotes.%20Not%20following%20the%20template%20might%20result%20in%20your%20request%20being%20denied.)
---

**Comment by CWKevo** [comment]
Please, include the URL to the extension.

**Comment by Alfaromeoman** [comment]
> Please, include the URL to the extension.
> 
> **Edit:** updated

Hello! Thank you very much for the reply! Do you mean the git hub url? It's here https://github.com/datlechin/flarum-title-length

**Comment by CWKevo** [comment]
> Hello! Thank you very much for the reply! Do you mean the git hub url? It's here https://github.com/datlechin/flarum-title-length

Yes! It's okay though, I've updated your original issue

**Comment by SKevo18** [comment]
Added
