### ISSUE TITLE
Please add the extension FoF Subscribed

### ISSUE THREAD

**Issue by flair-paul** [FreeFlarum/freeflarum.com#432]
### Extension URL

https://github.com/FriendsOfFlarum/subscribed

### Why should we install this extension?

So that admins and/or moderators can be notified by email each time a new user registers.

**Comment by dcardeneo** [comment]
I would, also, like to request this extension for our forum.  We have a very specific use case which requires this notification (in the past we used phpBB which provided this functionality and we are in the process of moving to a more 'modern' forum with enhancements to the user experience not available in phpBB).

**Comment by h8pewou** [comment]
We would also love this extension. We just donated, but happy to do so again if it gets implemented. :)

**Comment by SKevo18** [comment]
Added, since `follow-tags` and `follow-users` was included too and FreeFlarum's mail server has matured since
