### ISSUE TITLE
jeromegillard/map

### ISSUE THREAD

**Issue by Profi420** [FreeFlarum/freeflarum.com#435]
### Extension URL

https://packagist.org/packages/jeromegillard/map

### Why should we install this extension?

Map extension: display a map, a GPX or a GeoJSON file in a post
[https://discuss.flarum.org/d/31732](https://discuss.flarum.org/d/31732-map-extension-display-a-map-a-gpx-or-a-geojson-file-in-a-post)

**Comment by SKevo18** [comment]
Installed
