### ISSUE TITLE
finteger / guest 

### ISSUE THREAD

**Issue by Profi420** [FreeFlarum/freeflarum.com#436]
### Extension URL

https://packagist.org/packages/finteger/guest

### Why should we install this extension?

Guests are really just users with automatically generated email and password. The extension checks if a guest already exists before creating a new one, otherwise it just logs in the same guest as the one that exists in the database (by an IP check). This is to ensure that one IP address cannot create multiple guest registrations in your user table.
https://discuss.flarum.org/d/32759-free-guest-login-extension

**Comment by Romantomenko777** [comment]
https://support.freeflarum.com/d/17-fintegerguest
