### ISSUE TITLE
Digest : flarum-ext-digest

### ISSUE THREAD

**Issue by jaypatelani** [FreeFlarum/freeflarum.com#437]
### Extension URL

https://packagist.org/packages/blomstra/digest

### Why should we install this extension?

I think it is most useful for community forums more discussion is done here I miss this feature from discourse forum I had : 

https://discuss.flarum.org/d/2835-weekly-digest-email-feature

**Comment by Romantomenko777** [comment]
https://support.freeflarum.com/d/16-d2835-weekly-digest-email-feature
