### ISSUE TITLE
Fof/GeoIP - Extension Request

### ISSUE THREAD

**Issue by ItsGamingTube** [FreeFlarum/freeflarum.com#438]
### Extension URL

https://packagist.org/packages/fof/geoip

### Why should we install this extension?

This extension is very useful and can help combating spam and alt accounts, because with this extension you can find a post's geolocation (IP), and a moderator can use it to ban rule breakers easily.

**Comment by Romantomenko777** [comment]
https://support.freeflarum.com/d/15-fofgeoip
