### ISSUE TITLE
FoF/Pwned Passwords - Extension Request

### ISSUE THREAD

**Issue by ItsGamingTube** [FreeFlarum/freeflarum.com#439]
### Extension URL

https://packagist.org/packages/fof/pwned-passwords

### Why should we install this extension?

This extension can improve user's security by checking if the password the user is using is compromised or not. Not only that, but this will help prevent combating accounts hacking and improve user's security.

**Comment by Romantomenko777** [comment]
https://support.freeflarum.com/d/14-fofpwned-passwords
