### ISSUE TITLE
Minecraft server status extension 

### ISSUE THREAD

**Issue by WorldOfChuaHe** [FreeFlarum/freeflarum.com#440]
### Extension URL

https://packagist.org/packages/lukasss93/minecraft-server-status

### Why should we install this extension?

This extension will help the admins of the minecraft servers to create a forum for their servers and adding this extension will help the players in the server to see if the minecraft server is up and running.

**Comment by SKevo18** [comment]
Unfortunately, this is not a Flarum extension, but a PHP library for pinging Minecraft servers, so this can't be added. Sorry

As FreeFlarum does not develop any Flarum extensions, your best option is to submit a proposal at https://discuss.flarum.org and wait for someone to create an extension out of it
