### ISSUE TITLE
flarum-ext-email-whitelist

### ISSUE THREAD

**Issue by utc425937** [FreeFlarum/freeflarum.com#441]
### Extension URL

https://packagist.org/packages/clarkwinkelmann/flarum-ext-email-whitelist

### Why should we install this extension?

This extension allows whitelisting or blacklisting email addresses.If enabled, i can restrict forum users to small groups like campus to reduce server pressure.

**Comment by googologygithub** [comment]
这个挺好，还可以防止轰炸机。

**Comment by Romantomenko777** [comment]
https://support.freeflarum.com/d/13-clarkwinkelmannflarum-ext-email-whitelist
