### ISSUE TITLE
Flarum-ext-autoimage

### ISSUE THREAD

**Issue by lemonuwu08** [FreeFlarum/freeflarum.com#442]
### Extension URL

https://packagist.org/packages/ozzzzam/flarum-ext-autoimage

### Why should we install this extension?

It will automatically turn image links into images in composer, so Flarum member can easily see the preview image while compose.
Hope it is considered, Thanks a lot.

**Comment by Romantomenko777** [comment]
https://support.freeflarum.com/d/12-ozzzzamflarum-ext-autoimage
