### ISSUE TITLE
Audio BBCode

### ISSUE THREAD

**Issue by whisperwow** [FreeFlarum/freeflarum.com#444]
### Extension URL

https://discuss.flarum.org/d/21687-audio-bbcode-add-on

### Why should we install this extension?

This audio extension already works with FOF Upload and gives a template to FOF Upload to create a beautiful audio player for the audio files that you upload to flarum. I prefer to use this instead of the Inline Audio player which just creates a clickable link but discloses your uploaded file location making it too easy for someone to download the audio file directly.

**Comment by SKevo18** [comment]
Was abandoned on 28 Aug, but keeping this open for now until an alternative is found

**Comment by SKevo18** [comment]
Possible alternative: https://extiverse.com/extension/2nrwls/audio
