### ISSUE TITLE
FoF Mason

### ISSUE THREAD

**Issue by lemonuwu08** [FreeFlarum/freeflarum.com#445]
### Extension URL

https://packagist.org/packages/fof/mason

### Why should we install this extension?

It simply add custom fields to the discussions:
- Create custom fields with name, icon and description
- Fields can be required or optional
- Fields accept a dropdown selector or user-provided answers
- User answers can be validated with custom Laravel Validator rules
- Can choose the number of columns of the layout, show the tags field as a Mason field
I love this extension, so hope FreeFlarum can add this to admin panel. Thank you.

**Comment by SKevo18** [comment]
Already seemed to be included
