### ISSUE TITLE
Default Image Alt Text

### ISSUE THREAD

**Issue by tegmire** [FreeFlarum/freeflarum.com#446]
### Extension URL

https://packagist.org/packages/clarkwinkelmann/flarum-ext-default-image-alt

### Why should we install this extension?

Alt-text on images helps screenreaders describe images to all visually impaired users and allows for better SEO for your forum.

**Comment by Romantomenko777** [comment]
https://support.freeflarum.com/d/10-clarkwinkelmannflarum-ext-default-image-alt
