### ISSUE TITLE
Blog Article Series

### ISSUE THREAD

**Issue by Enzeekay** [FreeFlarum/freeflarum.com#448]
### Extension URL

https://packagist.org/packages/askvortsov/flarum-article-series

### Why should we install this extension?

This allows you to create article series by labelling discussions with certain secondary tags.

This is very useful for blogs on flarum, helping divide long series into multiple articles can be published on scheduled basis to not overwhelming the readers.

**Comment by Romantomenko777** [comment]
https://support.freeflarum.com/d/9-askvortsovflarum-article-series
