### ISSUE TITLE
Extension : id slug

### ISSUE THREAD

**Issue by wyatt1112** [FreeFlarum/freeflarum.com#449]
### Extension URL

https://extiverse.com/extension/pipecraft/flarum-ext-id-slug

### Why should we install this extension?

The default two link drivers will make the page link very long, so a function is needed to make the link only have an id, which id-slug can do. This is very important.

**Comment by Romantomenko777** [comment]
https://support.freeflarum.com/d/8-pipecraftflarum-ext-id-slug
