### ISSUE TITLE
BBCode More:More BBCode code

### ISSUE THREAD

**Issue by carrotwebgithub** [FreeFlarum/freeflarum.com#450]
### Extension URL

https://discuss.flarum.org.cn/d/4227

### Why should we install this extension?

 Excuse me, recently found a plugin 'BBCode More', this plugin is used in resource sharing to make it easier for users to download files. I hope you will add this plugin. 
Thanks.
Links:https://discuss.flarum.org.cn/d/4227
打扰了，最近偶然间看到了一个插件‘BBCode More’，这个插件用在资源分享中可以更加让用户更便捷地下载文件。我希望您能添加上这个插件。
感谢
插件发布链接：https://discuss.flarum.org.cn/d/4227

If you also need this feature, please bother to like or comment on GitHub to make a statement
如果您也需要这个功能，请麻烦在GitHub上点个赞或评论以表态

**Comment by SKevo18** [comment]
Does this extension just add a fancy box around a link to a file? Why don't you use FoF Upload instead, which you can use to upload the file directly to (Free)Flarum instead of linking it from GitHub, etc...?

**Comment by Googologyer** [comment]
这名称应该改一下

**Comment by SKevo18** [comment]
> 这名称应该改一下

The request, along with the remaining ones, will be migrated to https://support.freeflarum.com/t/extension-requests soon, and this repository will no longer be used for extension requests.

**Comment by SKevo18** [comment]
I've mentioned this alternative in https://support.freeflarum.com/d/52
If this still sounds useful, a new request can be made at https://support.freeflarum.com/t/extension-requests
