### ISSUE TITLE
I would like to have more customization options for my forum

### ISSUE THREAD

**Issue by AgustinPrS** [FreeFlarum/freeflarum.com#451]
### Extension URL

https://github.com/the-turk/flarum-pallet-theme

### Why should we install this extension?

The original post on this topic is: https://discuss.flarum.org/d/27757-pallet-theme
It basically shows what this theme looks like within Flarum, it is a very good theme, I hope you can enjoy it.

**Comment by SKevo18** [comment]
This extension is unfortunately marked as incompatible, and cannot be included at FreeFlarum, sorry. Duplicate of #266
