### ISSUE TITLE
Flarum Auth0 Auth

### ISSUE THREAD

**Issue by SKevo18** [FreeFlarum/freeflarum.com#452]
### Extension URL

https://extiverse.com/extension/lodge104/flarum-ext-oauth-auth0

### Why should we install this extension?

*Requested via mail*

**Comment by SpicyCombo** [comment]
Hello,
I'm SpicyCombo, the user who informed for submission of this add-on on FreeFlarum.

Auth0 is an authentication system that you can use to authenticate via various third parties, and manage your users more conveniently and with more flexibility. These features have been deemed very useful by many higher businesses, and adding this add-on to Flarum will be able to benefit some owners of Flarum sites.

**Comment by Romantomenko777** [comment]
https://support.freeflarum.com/d/7-lodge104flarum-ext-oauth-auth0
