### ISSUE TITLE
Add "Spam Alert" extension

### ISSUE THREAD

**Issue by Googologyer** [FreeFlarum/freeflarum.com#454]
### Extension URL

https://extiverse.com/extension/imdong/flarum-ext-spam-alert

### Why should we install this extension?

Why was this plugin created?

* Might be able to stop the bombardment of meaningless content
* Can prevent bombers (like Fair Forum suffered miserably)
* It can prevent some people from posting information that violates laws and regulations/violates the rules of the discussion forum.

**Comment by SKevo18** [comment]
https://support.freeflarum.com/d/6-imdongflarum-ext-spam-alert
