### ISSUE TITLE
Traditional Chinese Translation

### ISSUE THREAD

**Issue by keyang556** [FreeFlarum/freeflarum.com#457]
### Extension URL

https://github.com/flarum-lang/chinese-traditional

### Why should we install this extension?

Same as this closed issue  https://github.com/FreeFlarum/freeflarum.com/issues/374

**Comment by SKevo18** [comment]
https://support.freeflarum.com/d/5-flarum-langchinese-traditional

**Comment by keyang556** [comment]
The page you requested could not be found. 
Return to FreeFlarum Support

**Comment by SKevo18** [comment]
> The page you requested could not be found. Return to FreeFlarum Support

Apologies, you had to be logged in, I've fixed that now
