### ISSUE TITLE
Please add extension "Flarum Japanese Language パック 2020" and “Korean language Extension”

### ISSUE THREAD

**Issue by W1ndys** [FreeFlarum/freeflarum.com#462]
### Extension URL

https://discuss.flarum.org/d/22631-japanese-language-pack
https://discuss.flarum.org/d/1114-korean-language-extension

### Why should we install this extension?

I want to provide Japanese and Korean services to visitors

**Comment by SKevo18** [comment]
Please, include only one extension at a time in your request.

The Japanese language pack is incompatible with the latest Flarum, I've included `flarum-lang/japanese` instead. Korean language is incompatible as well, and it seems that there is no replacement for it at the moment.

**Comment by W1ndys** [comment]
> japanese

thank you very much for your help

**Comment by W1ndys** [comment]
> Please, include only one extension at a time in your request.
> 
> The Japanese language pack is incompatible with the latest Flarum, I've included `flarum-lang/japanese` instead. Korean language is incompatible as well, and it seems that there is no replacement for it at the moment.

I have a question. How did you locate my freeflarum address? I clearly didn’t provide it to you.

> Please, include only one extension at a time in your request.
> 
> The Japanese language pack is incompatible with the latest Flarum, I've included `flarum-lang/japanese` instead. Korean language is incompatible as well, and it seems that there is no replacement for it at the moment.

I have a question. How did you locate my freeflarum address? I clearly didn’t provide it to you.

**Comment by W1ndys** [comment]
> 哪个地址？

My freeflarum management background😊😊😊

**Comment by SKevo18** [comment]
Sorry, I have no idea what you're talking about. I do not know your FreeFlarum forum URL. If you mean `flarum-lang/japanese`, then that's the ID of the extension. I think it was just your translator that mixed it up somehow.

**Comment by W1ndys** [comment]
> Sorry, I have no idea what you're talking about. I do not know your FreeFlarum forum URL. If you mean `flarum-lang/japanese`, then that's the ID of the extension. I think it was just your translator that mixed it up somehow.

Sorry, maybe my description is wrong. My description is exactly: "I want to know how you can distinguish that I need this plug-in and not others who need this plug-in." In other words, how do you determine who to use this plug-in, Which user's management background should the plug-in be added to?

**Comment by SKevo18** [comment]
Ah apologies, I understand now. Extensions are included globally for all forums, and can't be included individually for technical reasons and due to the way FreeFlarum is set up (all extension code files are linked together across all forums, to save disk space).

Because of this, the more extensions are enabled, the higher stress is put on the whole server, which slows down forums that do not even require the extension. That's why requests normally require 5 or more upvotes to be added. However, in case of light extensions (ones that are client-side, or do not have complicated background code), such as language packs, I tend to make an exception and include them without the necessary amount of upvotes on the request at GitHub.

**Comment by W1ndys** [comment]
> 啊抱歉，我现在明白了。所有论坛都全局包含扩展，并且由于技术原因和 FreeFlarum 的设置方式而无法单独包含（所有扩展代码文件在所有论坛上链接在一起，以节省磁盘空间）。
> 
> 因此，论坛管理员启用的扩展越多（有些扩展甚至为了启用而启用了他们不需要的扩展），整个服务器承受的压力就越大，这会减慢甚至不需要扩展的论坛的速度。扩大。这就是为什么请求通常需要 5 或更多赞成票才能添加。但是，如果是轻型扩展（仅在浏览器中工作，或者没有复杂的服务器端代码），例如语言包，我倾向于破例并包含它们，而无需对请求进行必要的赞成在 GitHub（这就是现在发生的事情）

Thank you, I understand. Extensions are set globally, but in order to reduce the burden on the server, only extensions that require more people will be opened. Thank you for the service you provide, which greatly reduces my personal burden on the server.

**Comment by W1ndys** [comment]
> Ah apologies, I understand now. Extensions are included globally for all forums, and can't be included individually for technical reasons and due to the way FreeFlarum is set up (all extension code files are linked together across all forums, to save disk space).
> 
> Because of this, the more extensions forum admins enable (some enable even the ones they don't need, for the sake of enabling them), the higher stress is put on the whole server, which slows down forums that do not even require the extension. That's why requests normally require 5 or more upvotes to be added. However, in case of light extensions (ones that work in the browser only, or do not have complicated server-side code), such as language packs, I tend to make an exception and include them without the necessary amount of upvotes on the request at GitHub (which is what happened now)

Thank you, I understand. Extensions are set globally, but in order to reduce the burden on the server, only extensions that require more people will be opened. Thank you for the service you provide, which greatly reduces my personal burden on the server.

**Comment by SKevo18** [comment]
You're welcome! Yes, exactly, but sometimes I can make an exception and include them anyways
