### ISSUE TITLE
please ingur-upload in china

### ISSUE THREAD

**Issue by W1ndys** [FreeFlarum/freeflarum.com#463]
### Extension URL

https://discuss.flarum.org.cn/d/1993

### Why should we install this extension?

ingur-upload

**Comment by SKevo18** [comment]
I do not speak Chinese, but I think that it says that the extension is incompatible. Can you confirm whether that's true please? If yes, it is unfortunately impossible to include it at FreeFlarum, sorry

**Comment by W1ndys** [comment]
> I do not speak Chinese, but I think that it says that the extension is incompatible. Can you confirm whether that's true please? If yes, it is unfortunately impossible to include it at FreeFlarum, sorry
> 
> FYI there is already an extension that handles Imgur image upload. Could you please explain why that one doesn't suit your needs?

Thank you, but I have another question. Because of the Great Firewall, images cannot be uploaded using imgur in mainland China. Is there any way to solve it?

**Comment by SKevo18** [comment]
Use FoF Upload with the local driver
