### ISSUE TITLE
Please add the "ID Slug" extension, thanks!

### ISSUE THREAD

**Issue by ikungame** [FreeFlarum/freeflarum.com#465]
### Extension URL

https://extiverse.com/extension/pipecraft/flarum-ext-id-slug

### Why should we install this extension?

Because this extension can change the default post long link to a short link.
Here's what it looks like:
 Before installation:
  http://exmaple.com/d/123-hello-world
  http://exmaple.com/d/123-hello-world/3
 After installation:
  http://exmaple.com/d/123
  http://exmaple.com/d/123/3

**Comment by SKevo18** [comment]
Duplicate of https://support.freeflarum.com/d/8-pipecraftflarum-ext-id-slug
