### ISSUE TITLE
Could you please add an extension to implement "Tencent QQ login or WeChat login or Chinese mobile phone number login"

### ISSUE THREAD

**Issue by W1ndys** [FreeFlarum/freeflarum.com#467]
### Extension URL

I don't know

### Why should we install this extension?

Could you please add an extension to implement "Tencent QQ login or WeChat login or Chinese mobile phone number login"

**Comment by SKevo18** [comment]
This extension request is invalid. An URL to the extension must be provided - this also means that the extension must be developed and stable. FreeFlarum does not create new extensions, only includes ones that were already made by the community.
