### ISSUE TITLE
wanecho/mobilelogin

### ISSUE THREAD

**Issue by W1ndys** [FreeFlarum/freeflarum.com#468]
### Extension URL

https://packagist.org/packages/wanecho/mobilelogin

### Why should we install this extension?

I'm deeply sorry for my mistake just now.
Could you please add an extension to implement "Tencent QQ login or WeChat login or Chinese mobile phone number login"

**Comment by SKevo18** [comment]
Migrated to https://support.freeflarum.com/d/73
