### ISSUE TITLE
Chevereto 

### ISSUE THREAD

**Issue by jmillerv** [FreeFlarum/freeflarum.com#469]
### Extension URL

Either: 
https://packagist.org/packages/akr/chevereto
or 
https://packagist.org/packages/zhujia18/chevereto

### Why should we install this extension?

Chevereto is both an open-source paid and self-hostable tool that would allow for communities to manage their own image uploader and could reduce strain on FreeFlarum's services.

**Comment by SKevo18** [comment]
Installed `akr/chevereto` (note: for the future, please only include one extension per request, https://support.freeflarum.com/t/extension-requests)
