### ISSUE TITLE
FoF Follow Tags

### ISSUE THREAD

**Issue by valterbarreira** [FreeFlarum/freeflarum.com#83]
> **Please request only 1 extension per issue!**

> **Bazaar or Upload extensions are not compatible with FreeFlarum. See [#18](https://github.com/gwillem/freeflarum.com/issues/18)**

__Packagist URL for extension:__
https://packagist.org/packages/fof/follow-tags

__Why we should install this extension?__
- You should install it because it's a useful feature to automatically follow discussions of tags that we are interested.

> ** We only honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote. **

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

>Flarum official forum has this extension

**Comment by gwillem** [comment]
It would generate too much mail. FreeFlarum pays for every generated mail, and we cannot afford to be a mail distributor unfortunately.

**Comment by CWKevo** [comment]
This extension will be considered, however there is still an issue with it generating too much E-mail, and thus there will be higher chance that mail providers will mark FreeFlarum's mail as spam.

**Comment by CWKevo** [comment]
I will include this for now and see how it performs
